name = "RegressionTables"
uuid = "d519eb52-b820-54da-95a6-98e1306fdade"
authors = ["Johannes Boehm <johannes.boehm@gmail.com>"]
version = "0.7.3"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[weakdeps]
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
GLFixedEffectModels = "bafb0ae5-e5f5-5100-81b6-6a55d777c812"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"

[extensions]
RegressionTablesFixedEffectModelsExt = "FixedEffectModels"
RegressionTablesGLFixedEffectModelsExt = "GLFixedEffectModels"
RegressionTablesGLMExt = "GLM"
RegressionTablesMixedModelsExt = "MixedModels"

[compat]
Aqua = "0.8"
Distributions = "0.21, 0.23, 0.24, 0.25"
FixedEffectModels = "1.9"
Format = "1.3"
GLFixedEffectModels = "0.5"
GLM = "1.3"
MixedModels = "4"
Statistics = "1"
StatsAPI = "1.6"
StatsBase = "0.32, 0.33, 0.34"
StatsModels = "0.7.3"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"